version: '3.5'

services:

  service_container:
    container_name: worker_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env 

    ports:
      - ${PORT}:${PORT}
